#!/bin/env bash

# HINT: You can test the result of this script using the following command:
# printf "install.sh\nbackup.sh\nsystem.log\nnginx.conf\nreadme.txt\n" | ./file-classifier

# This script reads a list of filenames (one per line) and counts them by type.

scripts=0
logs=0
configs=0
others=0

while IFS= read -r filename; do

    case "$filename" in
        *.sh)
            (( scripts++ ))
            ;;
        *.log)
            (( logs++ ))
            ;;
        *.conf)
            (( configs++ ))
            ;;
        *)
            (( others++ ))
            ;;
    esac

done
echo "Scripts (.sh): $scripts"
echo "Logs (.log): $logs"
echo "Configs (.conf): $configs"
echo "Others: $others"
